#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#374b73"
bspc config focused_border_color "#78a5fc" 

picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
start-pulseaudio-x11
